use gpui::{Hsla, hsla, rgb};

use crate::gui::state::events::EventKind;
use crate::gui::theme::Palette;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum JellyTone {
    Primary,
    Cyan,
    Warning,
    Neutral,
    Output,
    Success,
    Error,
}

#[derive(Clone, Copy)]
pub(crate) struct JellyMaterialToken {
    pub(crate) shell_start: Hsla,
    pub(crate) shell_mid: Hsla,
    pub(crate) shell_end: Hsla,
    pub(crate) shell_depth: f32,
    pub(crate) shell_alpha: f32,
    pub(crate) core_top: Hsla,
    pub(crate) core_bottom: Hsla,
    pub(crate) core_alpha: f32,
    pub(crate) rim: Hsla,
    pub(crate) specular: Hsla,
    pub(crate) inner_glow: Hsla,
    pub(crate) contact_shadow: Hsla,
    pub(crate) state_aura: Hsla,
    pub(crate) text: Hsla,
}

impl JellyMaterialToken {
    pub(crate) fn for_tone(tone: JellyTone, palette: &Palette) -> Self {
        match tone {
            JellyTone::Primary => Self {
                shell_start: palette.accent_2,
                shell_mid: rgb(0x6ddfff).into(),
                shell_end: palette.accent,
                shell_depth: 1.0,
                shell_alpha: 0.97,
                core_top: hsla(0., 0., 1., 0.84),
                core_bottom: hsla(190., 0.9, 0.9, 0.48),
                core_alpha: 0.56,
                rim: hsla(0., 0., 1., 0.76),
                specular: hsla(0., 0., 1., 0.72),
                inner_glow: hsla(187., 0.92, 0.82, 0.36),
                contact_shadow: hsla(193., 0.78, 0.28, 0.28),
                state_aura: palette.accent,
                text: rgb(0x075b70).into(),
            },
            JellyTone::Cyan => Self {
                shell_start: rgb(0x8ff4ff).into(),
                shell_mid: palette.accent,
                shell_end: rgb(0x009cd8).into(),
                shell_depth: 0.96,
                shell_alpha: 0.97,
                core_top: hsla(0., 0., 1., 0.82),
                core_bottom: hsla(188., 0.9, 0.9, 0.46),
                core_alpha: 0.54,
                rim: hsla(0., 0., 1., 0.78),
                specular: hsla(0., 0., 1., 0.72),
                inner_glow: hsla(184., 0.96, 0.78, 0.36),
                contact_shadow: hsla(190., 0.78, 0.26, 0.25),
                state_aura: palette.accent,
                text: rgb(0x075c67).into(),
            },
            JellyTone::Warning => Self {
                shell_start: rgb(0xffc66b).into(),
                shell_mid: rgb(0xffa83d).into(),
                shell_end: palette.warning,
                shell_depth: 0.92,
                shell_alpha: 0.95,
                core_top: hsla(0., 0., 1., 0.8),
                core_bottom: hsla(35., 0.94, 0.86, 0.42),
                core_alpha: 0.5,
                rim: hsla(0., 0., 1., 0.66),
                specular: hsla(0., 0., 1., 0.64),
                inner_glow: hsla(35., 0.92, 0.78, 0.34),
                contact_shadow: hsla(34., 0.76, 0.24, 0.25),
                state_aura: palette.warning,
                text: rgb(0x884900).into(),
            },
            JellyTone::Neutral => Self {
                shell_start: rgb(0xd7fbff).into(),
                shell_mid: rgb(0xb7f4ff).into(),
                shell_end: rgb(0xffc7df).into(),
                shell_depth: 0.84,
                shell_alpha: 0.92,
                core_top: hsla(0., 0., 1., 0.8),
                core_bottom: hsla(332., 0.78, 0.93, 0.38),
                core_alpha: 0.46,
                rim: palette.accent.opacity(0.54),
                specular: hsla(0., 0., 1., 0.62),
                inner_glow: hsla(188., 0.78, 0.82, 0.26),
                contact_shadow: hsla(210., 0.28, 0.24, 0.18),
                state_aura: palette.accent,
                text: rgb(0x233348).into(),
            },
            JellyTone::Output => Self {
                shell_start: rgb(0x9ee8ff).into(),
                shell_mid: rgb(0xddf7ff).into(),
                shell_end: rgb(0xffd7e8).into(),
                shell_depth: 0.7,
                shell_alpha: 0.9,
                core_top: hsla(0., 0., 1., 0.94),
                core_bottom: hsla(205., 0.72, 0.94, 0.68),
                core_alpha: 0.76,
                rim: hsla(0., 0., 1., 0.66),
                specular: hsla(0., 0., 1., 0.62),
                inner_glow: palette.accent_2.opacity(0.22),
                contact_shadow: hsla(210., 0.28, 0.24, 0.18),
                state_aura: palette.accent_2,
                text: rgb(0x233348).into(),
            },
            JellyTone::Success => Self {
                shell_start: rgb(0x85f7ca).into(),
                shell_mid: rgb(0x34d399).into(),
                shell_end: palette.success,
                shell_depth: 0.76,
                shell_alpha: 0.92,
                core_top: hsla(0., 0., 1., 0.95),
                core_bottom: hsla(150., 0.78, 0.90, 0.74),
                core_alpha: 0.78,
                rim: hsla(0., 0., 1., 0.7),
                specular: hsla(0., 0., 1., 0.66),
                inner_glow: palette.success.opacity(0.28),
                contact_shadow: palette.success.opacity(0.22),
                state_aura: palette.success,
                text: rgb(0x0b6b49).into(),
            },
            JellyTone::Error => Self {
                shell_start: rgb(0xffa1a1).into(),
                shell_mid: rgb(0xff6b7c).into(),
                shell_end: palette.error,
                shell_depth: 0.78,
                shell_alpha: 0.92,
                core_top: hsla(0., 0., 1., 0.92),
                core_bottom: hsla(4., 0.82, 0.90, 0.7),
                core_alpha: 0.76,
                rim: hsla(0., 0., 1., 0.62),
                specular: hsla(0., 0., 1., 0.58),
                inner_glow: palette.error.opacity(0.24),
                contact_shadow: palette.error.opacity(0.24),
                state_aura: palette.error,
                text: rgb(0x9b1c14).into(),
            },
        }
    }

    pub(crate) fn for_event(kind: EventKind, palette: &Palette) -> Self {
        match kind {
            EventKind::System => Self::for_tone(JellyTone::Neutral, palette),
            EventKind::Video | EventKind::Comments => Self::for_tone(JellyTone::Primary, palette),
            EventKind::Danmaku => Self::for_tone(JellyTone::Cyan, palette),
            EventKind::Output => Self::for_tone(JellyTone::Output, palette),
            EventKind::Warning => Self::for_tone(JellyTone::Warning, palette),
            EventKind::Success => Self::for_tone(JellyTone::Success, palette),
            EventKind::Failure => Self::for_tone(JellyTone::Error, palette),
        }
    }
}
